export const TodoApplicationConstants = {
  FETCH_ITEMS: 'FETCH_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  TOGGLE_ITEM_COMPLETE: 'TOGGLE_ITEM_COMPLETE',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_COMPLETED_ITEMS: 'REMOVE_COMPLETED_ITEMS',
  COMPLETE_ALL_ITEMS: 'COMPLETE_ALL_ITEMS',
};
